Forum_v1/Models/UserEdit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Forum_v1.Models
{
    public class UserEdit
    {
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        [Display(Name = "Adress")]
        public string Adress { get; set; }

        [Required]
        [Display(Name = "City")]
        public string City { get; set; }

        [Required]
        [Display(Name = "State")]
        public string State { get; set; }

        public byte[] UserPhoto { get; set; }

    }
}

Forum_v1/Controllers/UserEditController.cs
using Forum_v1.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Forum_v1.Controllers
{
    public class UserEditController : Controller
    {
        // GET: UserEdit
        private ApplicationDbContext context = new ApplicationDbContext();
        
        public ActionResult Index()
        {
            string userId = User.Identity.GetUserId();
            ApplicationUser UserE = context.Users.FirstOrDefault(x => x.Id == userId);
            UserEdit NewUser = new UserEdit();

            NewUser.Email = UserE.Email;
            NewUser.FirstName = UserE.FirstName;
            NewUser.LastName = UserE.LastName;
            NewUser.Adress = UserE.Adress;
            NewUser.City = UserE.City;
            NewUser.State = UserE.State;
            NewUser.UserPhoto = UserE.UserPhoto;

            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }

            return View(NewUser);
        }
        public ActionResult UserShow(string id)
        {
            string userId = User.Identity.GetUserId();
            ApplicationUser UserE = context.Users.FirstOrDefault(x => x.Id == id);
            UserEdit NewUser = new UserEdit();

            NewUser.Email = UserE.Email;
            NewUser.FirstName = UserE.FirstName;
            NewUser.LastName = UserE.LastName;
            NewUser.Adress = UserE.Adress;
            NewUser.City = UserE.City;
            NewUser.State = UserE.State;
            NewUser.UserPhoto = UserE.UserPhoto;

            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }
            ViewBag.id = id;
            return View(NewUser);
        }

        public ActionResult Edit()
        {
            string userId = User.Identity.GetUserId();
            ApplicationUser UserE = context.Users.FirstOrDefault(x => x.Id == userId);
            UserEdit NewUser = new UserEdit();
            NewUser.Email = UserE.Email;
            NewUser.FirstName = UserE.FirstName;
            NewUser.LastName = UserE.LastName;
            NewUser.Adress = UserE.Adress;
            NewUser.City = UserE.City;
            NewUser.State = UserE.State;
            NewUser.UserPhoto = UserE.UserPhoto;
            return View(NewUser);
        }
        [HttpPut]
        public ActionResult Edit([Bind(Exclude = "UserPhoto")] UserEdit model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    byte[] imageData = null;
                    if (Request.Files.Count > 0)
                    {
                        HttpPostedFileBase poImgFile = Request.Files["UserPhoto"];
                            using (var binary = new BinaryReader(poImgFile.InputStream))

                            {
                                imageData = binary.ReadBytes(poImgFile.ContentLength);
                            }
                    }
                    string userId = User.Identity.GetUserId();
                    ApplicationUser UserEdited = context.Users.FirstOrDefault(x => x.Id == userId);
                    /*
                    if (TryUpdateModel(UserEdited))
                    {
                        UserEdited.FirstName = model.FirstName;
                        UserEdited.LastName = model.LastName;
                        UserEdited.Adress = model.Adress;
                        UserEdited.City = model.City;
                        UserEdited.State = model.State;
                        UserEdited.UserPhoto = imageData;
                        context.SaveChanges();
                        TempData["message"] = "Profilul a fost editat!";
                    }
                   */
                    UserEdited.FirstName = model.FirstName;
                    UserEdited.LastName = model.LastName;
                    UserEdited.Adress = model.Adress;
                    UserEdited.City = model.City;
                    UserEdited.State = model.State;
                    if (imageData != null && imageData.Length > 0)
                        UserEdited.UserPhoto = imageData;
                    context.SaveChanges();
                    TempData["message"] = "Profilul a fost editat!";
                    return RedirectToAction("Index");

                }
                else
                {
                    return View(model);
                }
            }
            catch (Exception e )
            {
                return View(model);
            }
        }
    }
}

Forum_v1/Views/UserEdit/Edit.cshtml
@model Forum_v1.Models.UserEdit
@{
    ViewBag.Title = "Edit Profile";
}

<div class="row" style="margin-top:10px">
    <div class="col-sm-10"><h3 class="text_color">@Html.DisplayFor(m => m.Email)</h3></div>
    <div class="col-sm-2"><a href="/users" class="pull-right"><img title="profile image" class="img-circle img-responsive" src="http://www.gravatar.com/avatar/28fd20ccec6865e2d5f0e1f4446eb7bf?s=100"></a></div>
</div>
<div class="row">
    <div class="col-sm-3">
        <!--left col-->


        <div class="text-center">
            <img src="@Url.Action("UserPhotos","Home")" class="avatar img-circle img-thumbnail" alt="avatar">
        </div><br>
        <div class="panel panel-default">
            <div class="panel-heading" id="wh">
                <p class="text_colorr"> Website</p>
            </div>
            <div class="panel-body">
            <a href="http://bootnipets.com">
                bootnipets.com
            </a>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading" id="wh"> 
                <p class="text_colorr">
                    Social Media
                </p>
            </div>
            <div class="panel-body">
                <i class="fa fa-facebook fa-2x"></i> <i class="fa fa-github fa-2x"></i> <i class="fa fa-twitter fa-2x"></i> <i class="fa fa-pinterest fa-2x"></i> <i class="fa fa-google-plus fa-2x"></i>
            </div>
        </div>

    </div><!--/col-3-->
    <div class="col-sm-9">
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" style="color:#fff" id="wh" href="#home">Home</a></li>
        </ul>


        <div class="tab-content">
            <div class="tab-pane active" id="home">
                <form class="form" action="/UserEdit/Edit" method="post" id="registrationForm" enctype = "multipart/form-data">
                    @Html.HttpMethodOverride(HttpVerbs.Put)
                    <div class="form-group">

                        <div class="col-xs-6">
                            @Html.Label("FirstName", "First Name", new { @class = "text_color"})
                            @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.FirstName, null, new { @class = "text-danger " })
                        </div>
                    </div>
                    <div class="form-group">

                        <div class="col-xs-6">
                            @Html.Label("LastName", "Last Name", new { @class = "text_color" })
                            @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.LastName, null, new { @class = "text-danger " })
                        </div>
                    </div>

                    <div class="form-group">

                        <div class="col-xs-6">
                            @Html.Label("Adress", "Adress", new { @class = "text_color" })
                            @Html.TextBoxFor(m => m.Adress, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Adress, null, new { @class = "text-danger " })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-xs-6">
                            @Html.Label("City", "City", new { @class = "text_color" })
                            @Html.TextBoxFor(m => m.City, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.City, null, new { @class = "text-danger " })
                        </div>
                    </div>
                    <div class="form-group">

                        <div class="col-xs-6">
                            @Html.Label("State", "State", new { @class = "text_color" })
                            @Html.TextBoxFor(m => m.State, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.State, null, new { @class = "text-danger " })
                        </div>
                    </div>
                    <div class="form-group">

                        <div class="col-xs-6">
                            @Html.Label("Upload a new photo ...", "Upload a new photo...", new { @class = "text_color" })
                            <input type="file" class="text_color text-center center-block file-upload" name="UserPhoto" id="fileUpload" accept=".png,.jpg,.gif,.tif" style="margin-left: 0px;"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <br>
                            <button class="btn btn-lg text_colorr" id="wh" type="submit"><i class="glyphicon glyphicon-ok-sign"></i> Save</button>
                        </div>
                    </div>
                    <hr class="hr_class" />
                </form>

                <hr>

            </div><!--/tab-pane-->
        </div><!--/tab-content-->

    </div><!--/col-9-->
</div><!--/row-->

Forum_v1/Views/UserEdit/Index.cshtml
@model Forum_v1.Models.UserEdit
@{
    ViewBag.Title = "Index";
}
@if (TempData.ContainsKey("message"))
{
    <h3 class="alert alert-info" role="alert">@ViewBag.message</h3>
}

<div class="row" style="margin-top:10px">
    <div class="col-sm-10 text_color"><h3>@Html.DisplayFor(m => m.Email)</h3></div>
    <div class="col-sm-2"><a href="/users" class="pull-right"><img title="profile image" class="img-circle img-responsive" src="http://www.gravatar.com/avatar/28fd20ccec6865e2d5f0e1f4446eb7bf?s=100"></a></div>
</div>
<div class="row">
    <div class="col-sm-3">
        <!--left col-->

        <div class="text-center">
            <img src="@Url.Action("UserPhotos","Home")" class="avatar img-circle img-thumbnail" alt="avatar">
        </div><br>


        <div class="panel panel-default">
            <div class="panel-heading" id="wh">
                <p class="text_colorr">Website</p>
            </div>
            <div class="panel-body">
                <a href="http://bootnipets.com">bootnipets.com</a>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading" id="wh">
                <p class="text_colorr">Social Media</p>
            </div>
            <div class="panel-body">
                <i class="fa fa-facebook fa-2x"></i> <i class="fa fa-github fa-2x"></i> <i class="fa fa-twitter fa-2x"></i> <i class="fa fa-pinterest fa-2x"></i> <i class="fa fa-google-plus fa-2x"></i>
            </div>
        </div>

    </div><!--/col-3-->
    <div class="col-sm-9">
        <ul class="nav nav-tabs">
            <li class="active" ><a data-toggle="tab" style="color:#fff " id="wh" href="#home">Home</a></li>
        </ul>


        <div class="tab-content">
            <div class="tab-pane active" id="home">
                        <div class="col-xs-6">
                           <h4 class="text_color"> @Html.Label("FirstName", "First Name") </h4>
                           <p class="text_colorr"> @Html.DisplayFor(m => m.FirstName) </p>
                        </div>
                    
                    
                        <div class="col-xs-6">
                          <h4 class="text_color">  @Html.Label("LastName", "Last Name") </h4>

                          <p class="text_colorr">@Html.DisplayFor(m => m.LastName)</p>
                        </div>
                    
                    
                        <div class="col-xs-6">
                            <h4 class="text_color"> @Html.Label("Adress", "Adress") </h4>
                            <p class="text_colorr"> @Html.DisplayFor(m => m.Adress)</p>
                        </div>
                    
                 
                        <div class="col-xs-6">
                            <h4 class="text_color"> @Html.Label("City", "City") </h4>
                            <p class="text_colorr"> @Html.DisplayFor(m => m.City)</p>
                        </div>
                   
                        <div class="col-xs-6">
                            <h4 class="text_color">  @Html.Label("State", "State") </h4>
                           <p class="text_colorr"> @Html.DisplayFor(m => m.State) </p>
                        </div>
                    
                        <div class="col-xs-12">
                            <br>
                            <a href='@Url.Action("Edit", "UserEdit")' class="btn btn-primary">Edit</a>
                        </div>
            </div><!--/tab-pane-->
        </div><!--/tab-content-->

    </div><!--/col-9-->
</div><!--/row-->

Forum_v1/Views/UserEdit/UserShow.cshtml
@model Forum_v1.Models.UserEdit
@{
    ViewBag.Title = "Index";
}
@if (TempData.ContainsKey("message"))
{
    <h3 class="alert alert-info" role="alert">@ViewBag.message</h3>
}

<div class="row" style="margin-top:10px">
    <div class="col-sm-10 text_color"><h3>@Html.DisplayFor(m => m.Email)</h3></div>
    <div class="col-sm-2"><a href="/users" class="pull-right"><img title="profile image" class="img-circle img-responsive" src="http://www.gravatar.com/avatar/28fd20ccec6865e2d5f0e1f4446eb7bf?s=100"></a></div>
</div>
<div class="row">
    <div class="col-sm-3">
        <!--left col-->

        <div class="text-center">
            <img src="@Url.Action("GetPhoto","Home", new { id = ViewBag.id})" class="avatar img-circle img-thumbnail" alt="avatar">
        </div><br>


        <div class="panel panel-default">
            <div class="panel-heading" id="wh">
                <p class="text_colorr">Website</p>
            </div>
            <div class="panel-body">
                <a href="http://bootnipets.com">bootnipets.com</a>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading" id="wh">
                <p class="text_colorr">Social Media</p>
            </div>
            <div class="panel-body">
                <i class="fa fa-facebook fa-2x"></i> <i class="fa fa-github fa-2x"></i> <i class="fa fa-twitter fa-2x"></i> <i class="fa fa-pinterest fa-2x"></i> <i class="fa fa-google-plus fa-2x"></i>
            </div>
        </div>

    </div><!--/col-3-->
    <div class="col-sm-9">
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" style="color:#fff " id="wh" href="#home">Home</a></li>
        </ul>


        <div class="tab-content">
            <div class="tab-pane active" id="home">
                <div class="col-xs-6">
                    <h4 class="text_color"> @Html.Label("FirstName", "First Name") </h4>
                    <p class="text_colorr"> @Html.DisplayFor(m => m.FirstName) </p>
                </div>


                <div class="col-xs-6">
                    <h4 class="text_color">  @Html.Label("LastName", "Last Name") </h4>

                    <p class="text_colorr">@Html.DisplayFor(m => m.LastName)</p>
                </div>


                <div class="col-xs-6">
                    <h4 class="text_color"> @Html.Label("Adress", "Adress") </h4>
                    <p class="text_colorr"> @Html.DisplayFor(m => m.Adress)</p>
                </div>


                <div class="col-xs-6">
                    <h4 class="text_color"> @Html.Label("City", "City") </h4>
                    <p class="text_colorr"> @Html.DisplayFor(m => m.City)</p>
                </div>

                <div class="col-xs-6">
                    <h4 class="text_color">  @Html.Label("State", "State") </h4>
                    <p class="text_colorr"> @Html.DisplayFor(m => m.State) </p>
                </div>
            </div><!--/tab-pane-->
        </div><!--/tab-content-->

    </div><!--/col-9-->
</div><!--/row-->