Forum_v1/Models/Message.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Forum_v1.Models
{
    public class Message
    {
        [Key]
        public int MessageId { get; set; }

        [Required(ErrorMessage = "Mesajul nu poate fi gol")]
        [DataType(DataType.MultilineText)]
        public string Text { get; set; }
        [Required]
        public DateTime Date { get; set; }

        public string UserId { get; set; }
        public virtual ApplicationUser User { get; set; }

        public int SubjectID { get; set; }
        public Subject Subject { get; set; }
    }
}

Forum_v1/Controllers/ImageController.cs
using Forum_v1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Forum_v1.Controllers
{
    public class ImageController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Image
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Show(string id)
        {
            ApplicationUser UserE = db.Users.FirstOrDefault(x => x.Id == id);
            var imageData = UserE.UserPhoto;

            return File(imageData, "imageUser/jpg");
        }
    }
}

Forum_v1/Controllers/MessagesController.cs
using Forum_v1.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Forum_v1.Controllers
{
    public class MessagesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Subjects
        public ActionResult Index(int? id)
        {
            ViewBag.SubjectId = id;
            Subject Subject = db.Subjects.Find(id);
            ViewBag.Subject = Subject;
            var mesaje = from Message in Subject.Messages select Message;
            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }

            return View(mesaje.ToList());
        }
        [Authorize(Roles = "User,Moderator,Administrator")]
        public ActionResult Create(int? id)
        {
            //Debug.WriteLine(id);
            ViewBag.SubjectId = id;
            return View("Create");

        }
        [Authorize(Roles = "User,Moderator,Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MessageId,Text,Date,UserId,SubjectID")] Message message)
        {
            message.UserId = User.Identity.GetUserId();
            message.Date = DateTime.Now;
            /*Debug.WriteLine(subject.SubjectId);
            Debug.WriteLine(subject.Title);
            Debug.WriteLine(subject.Description);
            Debug.WriteLine(subject.Date);
            Debug.WriteLine(subject.UserId);*/
            //Debug.WriteLine(subject.CategoryID);

            if (ModelState.IsValid)
            {
                //Debug.WriteLine("A ajuns unde trebuie");
                db.Messages.Add(message);
                db.SaveChanges();
                return Redirect("/Messages/Index/" + message.SubjectID);

            }
            else
            {
                ViewBag.SubjectId = message.SubjectID;
                return View("Create");
            }
        }
        [Authorize(Roles = "User,Moderator,Administrator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = db.Messages.Find(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            if (message.UserId == User.Identity.GetUserId() || User.IsInRole("Administrator") || User.IsInRole("Moderator"))
            {
                ViewBag.message = message;
                return View(message);
            }
            else
            {
                TempData["message"] = "Nu aveti dreptul de a modifca mesaje care nu va apartin!";
                return Redirect("/Messages/Index/" + message.SubjectID);
            }
        }

        [HttpPut]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User,Moderator,Administrator")]
        public ActionResult Edit(int MessageId, Message newData)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    Message message = db.Messages.Find(MessageId);
                    if (message.UserId == User.Identity.GetUserId() || User.IsInRole("Administrator") || User.IsInRole("Moderator"))
                    {
                        if (TryUpdateModel(message))
                        {
                            message.Text = newData.Text;
                            db.SaveChanges();
                            TempData["message"] = "Mesajul a fost editat cu succes";
                        }

                        return Redirect("/Messages/Index/" + message.SubjectID);
                    }
                    else
                    {
                        TempData["message"] = "Nu aveti dreptul de a modifca mesaje care nu sunt create de dumneavoastra!";
                        return Redirect("/Messages/Index/" + message.SubjectID);
                    }
                }
                else
                {
                    return View();
                }
            }
            catch (Exception e)
            {
                return View();
            }
        }
        [Authorize(Roles = "User,Moderator,Administrator")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = db.Messages.Find(id);

            if (message == null)
            {
                return HttpNotFound();
            }

            if (message.UserId == User.Identity.GetUserId() || User.IsInRole("Administrator") || User.IsInRole("Moderator"))
            {
                ViewBag.message = message;
                return View(message);
            }
            else
            {
                TempData["message"] = "Nu aveti dreptul de a sterge mesaje care nu va apartin!";
                return Redirect("/Messages/Index/" + message.SubjectID);
            }
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User,Moderator,Administrator")]
        public ActionResult DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = db.Messages.Find(id);

            if (message == null)
            {
                return HttpNotFound();
            }
            if (message.UserId == User.Identity.GetUserId() || User.IsInRole("Administrator") || User.IsInRole("Moderator"))
            {
                db.Messages.Remove(message);
                db.SaveChanges();
                TempData["message"] = "Mesajul a fost sters!";
                return Redirect("/Messages/Index/" + message.SubjectID);

            }
            else
            {
                TempData["message"] = "Nu aveti dreptul de a sterge mesaje care nu va apartin!";
                return Redirect("/Messages/Index/" + message.SubjectID);
            }
        }
    }
}

Forum_v1/Controllers/SubjectsController.cs
using Forum_v1.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Forum_v1.Controllers
{
    public class SubjectsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Subjects
        public ActionResult Index(int? id, int page = 0, int sortare = 0)
        {
            ViewBag.CategoryId = id;
            Category Category = db.Categories.Find(id);
            ViewBag.Category = Category;
            var subiecte = from Subject in Category.Subjects select Subject;
            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }
            var subiectele = subiecte.ToList();

            int nrSub = subiecte.ToList().Count();
            ViewBag.NrPages = nrSub / 10;
            if (nrSub % 10 != 0)
                ViewBag.NrPages = ViewBag.NrPages + 1;

            if (page < 0)
                page = 0;
            ViewBag.pagina = page;
            if (((page * 10) > subiectele.Count() - 1))
            {
                page = ViewBag.NrPages - 1;
                ViewBag.pagina = ViewBag.NrPages;
            }


            if (sortare == 0) ViewBag.tipSort = 0;//sortare==0 inseamna ordonare dupa data de la cel mai vechi la cel mai nou, nu e nevoie de sortare
            if (sortare == 1)    //sortare==1 inseamna ordonare alfabetica dupa titlu
            {
                subiecte = subiecte.OrderBy(o => o.Title).ToList();
                ViewBag.tipSort = 1;
            }
            if (sortare == 2)    //sortare==2 inseamna sortare dupa numele creatorului subiectului
            {
                subiecte = subiecte.OrderBy(o => o.User.FirstName).ThenBy(o => o.User.LastName).ToList();
                ViewBag.tipSort = 2;
            }
            if (sortare == 3)    //sortare==3 inseamna sortare dupa data, de la cel mai nou la cel mai vechi
            {
                subiecte = subiecte.OrderByDescending(o => o.Date).ToList();
                ViewBag.tipSort = 3;
            }
            if (subiectele.Count() == 0)
                return View(subiecte.ToList());
            if ((page * 10) + 9 <= subiectele.Count() - 1)
                return View(subiecte.ToList().GetRange(page * 10, 10));
            else
                return View(subiecte.ToList().GetRange(page * 10, subiectele.Count() - (page * 10)));
        }
        [Authorize(Roles = "User,Moderator,Administrator")]
        public ActionResult Create(int? id)
        {
            Debug.WriteLine(id);
            ViewBag.CategoryId = id;
            return View("Create");

        }
        [Authorize(Roles = "User,Moderator,Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SubjectID,Title,Description,Date,UserId,CategoryID")] Subject subject)
        {
            subject.UserId = User.Identity.GetUserId();
            subject.Date = DateTime.Now;
            /*Debug.WriteLine(subject.SubjectId);
            Debug.WriteLine(subject.Title);
            Debug.WriteLine(subject.Description);
            Debug.WriteLine(subject.Date);
            Debug.WriteLine(subject.UserId);*/
            //Debug.WriteLine(subject.CategoryID);
            if (ModelState.IsValid)
            {
                //Debug.WriteLine("A ajuns unde trebuie");
                db.Subjects.Add(subject);
                db.SaveChanges();
                return Redirect("/Subjects/Index/" + subject.CategoryID);

            }
            else
            {
                ViewBag.CategoryId = subject.CategoryID;
                return View("Create");
            }

        }
        // GET: Categories/Edit/5
        [Authorize(Roles = "User,Moderator,Administrator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = db.Subjects.Find(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            if (subject.UserId == User.Identity.GetUserId() || User.IsInRole("Administrator") || User.IsInRole("Moderator"))
            {
                ViewBag.subject = subject;
                var categorii = GetAllCategories();
                ViewBag.ListaCategorii = categorii;
                ViewBag.categorie = subject.CategoryID.ToString();
                return View(subject);
            }
            else
            {
                TempData["message"] = "Nu aveti dreptul de a modifca subiecte care nu sunt create de dumneavoastra!";
                return Redirect("/Subjects/Index/" + subject.CategoryID);
            }
        }
        [NonAction]
        public IEnumerable<SelectListItem> GetAllCategories()
        {
            var selectList = new List<SelectListItem>();
            var categorii = from Category in db.Categories select Category;
            foreach (var categorie in categorii)
            {
                selectList.Add(new SelectListItem
                {
                    Value = categorie.CategoryID.ToString(),
                    Text = categorie.Title.ToString()
                });
            }
            return selectList;
        }
        [HttpPut]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User,Moderator,Administrator")]
        public ActionResult Edit(int SubjectId, Subject newData)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    Subject subject = db.Subjects.Find(SubjectId);
                    if (subject.UserId == User.Identity.GetUserId() || User.IsInRole("Administrator") || User.IsInRole("Moderator"))
                    {
                        if (TryUpdateModel(subject))
                        {
                            subject.Title = newData.Title;
                            subject.Description = newData.Description;
                            if (User.IsInRole("Administrator") || User.IsInRole("Moderator"))
                            {
                                subject.CategoryID = Int32.Parse(HttpContext.Request.Params.Get("newCategory"));
                            }
                            db.SaveChanges();
                            TempData["message"] = "Subiect editat cu succes";
                        }

                        return Redirect("/Subjects/Index/" + subject.CategoryID);
                    }
                    else
                    {
                        TempData["message"] = "Nu aveti dreptul de a modifca subiecte care nu sunt create de dumneavoastra!";
                        return Redirect("/Subjects/Index/" + subject.CategoryID);
                    }
                }
                else
                {
                    return View();
                }
            }
            catch (Exception e)
            {
                return View();
            }
        }

        [Authorize(Roles = "User,Moderator,Administrator")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = db.Subjects.Find(id);

            if (subject == null)
            {
                return HttpNotFound();
            }
            ViewBag.SubTitle = subject.Title;
            ViewBag.subject = subject;
            if (subject.UserId == User.Identity.GetUserId() || User.IsInRole("Administrator") || User.IsInRole("Moderator"))
            {
                ViewBag.subject = subject;
                return View(subject);
            }
            else
            {
                TempData["message"] = "Nu aveti dreptul de a sterge subiecte care nu sunt create de dumneavoastra!";
                return Redirect("/Subjects/Index/" + subject.CategoryID);
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User,Moderator,Administrator")]
        public ActionResult DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = db.Subjects.Find(id);

            if (subject == null)
            {
                return HttpNotFound();
            }
            if (subject.UserId == User.Identity.GetUserId() || User.IsInRole("Administrator") || User.IsInRole("Moderator"))
            {
                db.Subjects.Remove(subject);
                db.SaveChanges();
                TempData["message"] = "Subiectul a fost sters!";
                return Redirect("/Subjects/Index/" + subject.CategoryID);

            }
            else
            {
                TempData["message"] = "Nu aveti dreptul de a sterge subiecte care nu au fost create de dumneavoastra!";
                return Redirect("/Subjects/Index/" + subject.CategoryID);
            }
        }

    }
}

Forum_v1/Views/Messages/Create.cshtml
@model Forum_v1.Models.Message
@{
    ViewBag.Title = "CreateSubjectView";
}
<h2 class="text_color">Adauga Mesaj nou</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <form method="post" action="/Subjects/Create">
            <hr class="hr_class"/>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2 text_color" })
                <br /> <br />
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
                    <input type="hidden" name="SubjectId" value="@ViewBag.SubjectId" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit">Adauga Mesaj</button>
                </div>
            </div>
        </form>
    </div>
}

Forum_v1/Views/Messages/Delete.cshtml
@model Forum_v1.Models.Message
@{
    ViewBag.Title = "Delete";
}
<h3 class="text_color">Doriti sa stergeti mesajul ?</h3>
<div>
    <hr class="hr_class" />
    <div class="row">
        <div class="col-md-2">
            <p class="text_color"> Text: </p>
        </div>
        <div class="col-md-10">
           <p class="description"> @Html.DisplayFor(model => model.Text)</p>
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |

        </div>
        @Html.ActionLink("Back to Chat", "Index", "Messages", new { id = ViewBag.message.SubjectID }, null)
    }
</div>

Forum_v1/Views/Messages/Edit.cshtml
@model Forum_v1.Models.Message
@{
    ViewBag.Title = "Editeaza Mesajul";
}

<h2 class="text_color">Editare Mesaj</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <form method="post" action="/Messages/Edit/@ViewBag.message.MessageId">
            @Html.HttpMethodOverride(HttpVerbs.Put)
            <hr class="hr_class"/>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.MessageId)
            @Html.HiddenFor(model => model.SubjectID)
            @Html.HiddenFor(model => model.Date)
            @Html.HiddenFor(model => model.UserId)
            <div class="form-group">
                @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2 text_color" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </form>
    </div>
}
<div>
    <p>
        @{
            @Html.ActionLink("Back to Chat", "Index", "Messages", new { id = ViewBag.message.SubjectID }, null)
        }
    </p>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Forum_v1/Views/Messages/Index.cshtml
@model IEnumerable<Forum_v1.Models.Message>
@{
    ViewBag.Title = "Index";
}
<h1 class="text_color">@ViewBag.Subject.Title</h1>
@if (ViewBag.message != null)
{
    <div class="alert alert-success">
        <strong>@ViewBag.message</strong>
    </div>
}
@if (this.User.IsInRole("Administrator") || this.User.IsInRole("Moderator") || this.User.IsInRole("User"))
{
    <p>
        @{
            @Html.ActionLink("Adauga mesaj", "Create", "Messages", new { id = ViewBag.SubjectId }, null)
        }
    </p>
}
<p>
    @{
        @Html.ActionLink("Back to Subjects", "Index", "Subjects", new { id = ViewBag.Subject.CategoryID }, null)
    }
</p>
<div class="container-fluid">
    @foreach (var item in Model)
    {
        <hr class="hr_class" />
        <div class="row">
            <div class="col-md-4">
                <img src="@Url.Action( "Show", "Image", new { id = item.UserId } )" height="70" width="65" display="inline-block" />
                <h5 class="description">Autor: @Html.DisplayFor(modelItem => item.User.FirstName) @Html.DisplayFor(modelItem => item.User.LastName)</h5>
                <h5 class="description">data:@Html.DisplayFor(modelItem => item.Date)</h5>
                @if (this.User.IsInRole("Administrator") || this.User.IsInRole("Moderator") || this.User.IsInRole("User"))
                {
                    <p> @Html.ActionLink("Edit", "Edit", new { id = item.MessageId })       @Html.ActionLink("Delete", "Delete", new { id = item.MessageId }) </p>
                }
            </div>
            <div class="col-md-8 ">
                <p class="text_color">@Html.DisplayFor(modelItem => item.Text)</p>
            </div>

        </div>
    }
</div>