Forum_v1/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Forum_v1.Models;

namespace Forum_v1.Controllers
{
    public class CategoriesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Categories
        [Authorize(Roles = "User,Moderator,Administrator")]
        public ActionResult Index()
        {
            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }
            return View(db.Categories.ToList());
        }

        // GET: Categories/Details/5
        [Authorize(Roles = "User,Moderator,Administrator")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Categories/Create
        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            if (User.IsInRole("Administrator"))
            {
                return View();
            }
            else
            {
                ViewBag.message = "Trebuie sa fiti administrator pentru a crea categori!";
                return Redirect("/Account/Login/");
            }
       
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoryID,Title,Description")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                TempData["message"] = "Categoria a fot creata cu succes!";
                return RedirectToAction("/Home/Index");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            if (User.IsInRole("Administrator"))
            {
                return View(category);
            }
            else
            {
                ViewBag.message = "Trebuie sa fiti administrator pentru a edita categori!";
                return Redirect("/Account/Login/");
            }
            
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit([Bind(Include = "CategoryID,Title,Description")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                TempData["message"] = "Categoria a fot editata cu succes!";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["message"] = "Trebuie sa fiti administrator pentru a edita categoria!";
                return View(category);
            }
        }

        // GET: Categories/Delete/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            if (User.IsInRole("Administrator"))
            {
                return View(category);
            }
            else
            {
                ViewBag.message = "Trebuie sa fiti administrator pentru a sterge categoria!";
                return Redirect("/Account/Login/");
            }
        }

        // POST: Categories/Delete/5
        [Authorize(Roles = "Administrator")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            TempData["message"] = "Categoria a fot stearsa cu succes!";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Forum_v1/Controllers/MessagesController.cs
using Forum_v1.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Forum_v1.Controllers
{
    public class MessagesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Subjects
        public ActionResult Index(int? id)
        {
            ViewBag.SubjectId = id;
            Subject Subject = db.Subjects.Find(id);
            ViewBag.Subject = Subject;
            var mesaje = from Message in Subject.Messages select Message;
            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }

            return View(mesaje.ToList());
        }
        [Authorize(Roles = "User,Moderator,Administrator")]
        public ActionResult Create(int? id)
        {
            //Debug.WriteLine(id);
            ViewBag.SubjectId = id;
            return View("Create");

        }
        [Authorize(Roles = "User,Moderator,Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MessageId,Text,Date,UserId,SubjectID")] Message message)
        {
            message.UserId = User.Identity.GetUserId();
            message.Date = DateTime.Now;
            /*Debug.WriteLine(subject.SubjectId);
            Debug.WriteLine(subject.Title);
            Debug.WriteLine(subject.Description);
            Debug.WriteLine(subject.Date);
            Debug.WriteLine(subject.UserId);*/
            //Debug.WriteLine(subject.CategoryID);

            if (ModelState.IsValid)
            {
                //Debug.WriteLine("A ajuns unde trebuie");
                db.Messages.Add(message);
                db.SaveChanges();
                return Redirect("/Messages/Index/" + message.SubjectID);

            }
            else
            {
                ViewBag.SubjectId = message.SubjectID;
                return View("Create");
            }
        }
        [Authorize(Roles = "User,Moderator,Administrator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = db.Messages.Find(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            if (message.UserId == User.Identity.GetUserId() || User.IsInRole("Administrator") || User.IsInRole("Moderator"))
            {
                ViewBag.message = message;
                return View(message);
            }
            else
            {
                TempData["message"] = "Nu aveti dreptul de a modifca mesaje care nu va apartin!";
                return Redirect("/Messages/Index/" + message.SubjectID);
            }
        }

        [HttpPut]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User,Moderator,Administrator")]
        public ActionResult Edit(int MessageId, Message newData)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    Message message = db.Messages.Find(MessageId);
                    if (message.UserId == User.Identity.GetUserId() || User.IsInRole("Administrator") || User.IsInRole("Moderator"))
                    {
                        if (TryUpdateModel(message))
                        {
                            message.Text = newData.Text;
                            db.SaveChanges();
                            TempData["message"] = "Mesajul a fost editat cu succes";
                        }

                        return Redirect("/Messages/Index/" + message.SubjectID);
                    }
                    else
                    {
                        TempData["message"] = "Nu aveti dreptul de a modifca mesaje care nu sunt create de dumneavoastra!";
                        return Redirect("/Messages/Index/" + message.SubjectID);
                    }
                }
                else
                {
                    return View();
                }
            }
            catch (Exception e)
            {
                return View();
            }
        }
        [Authorize(Roles = "User,Moderator,Administrator")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = db.Messages.Find(id);

            if (message == null)
            {
                return HttpNotFound();
            }

            if (message.UserId == User.Identity.GetUserId() || User.IsInRole("Administrator") || User.IsInRole("Moderator"))
            {
                ViewBag.message = message;
                return View(message);
            }
            else
            {
                TempData["message"] = "Nu aveti dreptul de a sterge mesaje care nu va apartin!";
                return Redirect("/Messages/Index/" + message.SubjectID);
            }
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User,Moderator,Administrator")]
        public ActionResult DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = db.Messages.Find(id);

            if (message == null)
            {
                return HttpNotFound();
            }
            if (message.UserId == User.Identity.GetUserId() || User.IsInRole("Administrator") || User.IsInRole("Moderator"))
            {
                db.Messages.Remove(message);
                db.SaveChanges();
                TempData["message"] = "Mesajul a fost sters!";
                return Redirect("/Messages/Index/" + message.SubjectID);

            }
            else
            {
                TempData["message"] = "Nu aveti dreptul de a sterge mesaje care nu va apartin!";
                return Redirect("/Messages/Index/" + message.SubjectID);
            }
        }
    }
}

Forum_v1/Controllers/UsersController.cs
using Forum_v1.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Forum_v1.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class UsersController : Controller
    {
        private ApplicationDbContext db = ApplicationDbContext.Create();
        // GET: Users
        public ActionResult Index()
        {
            var users = from user in db.Users
                        orderby user.UserName
                        select user;
            ViewBag.UserList = users;
            return View();
        }
        
        public ActionResult Edit(string id)
        {
            ApplicationUser user = db.Users.Find(id);
            user.AllRoles = GetAllRoles();
            var userRole = user.Roles.FirstOrDefault();
            ViewBag.userRole = userRole.RoleId;
            return View(user);
        }
        [NonAction]
        public IEnumerable<SelectListItem> GetAllRoles()
        {
            var selectList = new List<SelectListItem>();
            var roles = from role in db.Roles select role;
            foreach (var role in roles)
            {
                selectList.Add(new SelectListItem
                {
                    Value = role.Id.ToString(),
                    Text = role.Name.ToString()
                });

            }
                return selectList;
            
        }
        [HttpPut]
        public ActionResult Edit (string id,ApplicationUser newData)
        {
            ApplicationUser user = db.Users.Find(id);
            user.AllRoles = GetAllRoles();
            var userRole = user.Roles.FirstOrDefault();
            ViewBag.userRole = userRole.RoleId;
            try
            {
                ApplicationDbContext context = new ApplicationDbContext();
                var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
               // if (TryUpdateModel(user))
               //{
                    user.UserName = newData.UserName;
                    user.Email = newData.Email;

                    var roles = from role in db.Roles select role;
                    foreach (var role in roles)

                    {
                        UserManager.RemoveFromRole(id, role.Name);
                    }
                    var selectedRole =
                        db.Roles.Find(HttpContext.Request.Params.Get("newRole"));
                    UserManager.AddToRole(id, selectedRole.Name);

                    db.SaveChanges();

                //}
                return RedirectToAction("Index");

            }
            catch (Exception e)
            {
                Response.Write(e.Message);
                return View(user);
            }
        }
    }

}

Forum_v1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Forum_v1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Forum_v1/Views/Home/Index.cshtml
@*model IEnumerable<Forum_v1.Models.Category>*@
@model Tuple<IEnumerable<Forum_v1.Models.Category>, IEnumerable<Forum_v1.Models.Subject>>
@{
    ViewBag.Title = "Home Page";
}

<div class="row" style="margin-top:15px;">

    <div class="col-md-8">
        
    </div>
    <div class="col-md-4">
        <img  style="float:right;" src="@Url.Action("GetLogo","Home")" class="avatar img-responsive" alt="avatar">
    </div>
</div>
<div class="row">
    <div class="col-md-2">
        <div class="row">
            <div class="col-xs-6">
                @Html.ActionLink("Members", "Index", "Users", null, new { @class = "btn btn-info" })
            </div>
            <div class="col-xs-6">
                <a class="btn btn-info" href="#">Calendar</a>
            </div>
        </div>
    </div>
    <div class="col-md-10">

    </div>
</div>
<br />
<hr class="hr_class" />
<div class="row text_color" id="my_style" style="margin-top:20px;">
    <div class="col-md-4">
        <h2 class="colorr">Subiecte noi</h2>
    </div>
    <div class="col-md-8">

        <div class="row">

            @{ int skip = 0;
                var Subject = Model.Item2.Skip(skip).Take(4);
                foreach (var item in Subject)
                {
                    <div class="col-xs-3">
                        @Html.ActionLink(item.Title, "Index", "Messages", new { id = item.SubjectId }, new { @class = "colorr" })
                    </div>
                }
                skip = skip + 4;
            }
        </div>
        <div class="row">

            @{
                Subject = Model.Item2.Skip(skip).Take(4);
                foreach (var item in Subject)
                {
                    <div class="col-xs-3">
                        @Html.ActionLink(item.Title, "Details", "Subjects", new { id = item.SubjectId }, new { @class = "colorr" })
                    </div>
                }
                skip = skip + 4;
            }
        </div>
        <div class="row">

            @{
                Subject = Model.Item2.Skip(skip).Take(4);
                foreach (var item in Subject)
                {
                    <div class="col-xs-3">
                        @Html.ActionLink(item.Title, "Details", "Subjects", new { id = item.SubjectId }, new { @class = "colorr" })
                    </div>
                }
            }
        </div>
    </div>
</div>
<br />
@if (this.User.IsInRole("Administrator"))
{
    <p>
        @Html.ActionLink("Create new category", "Create","Categories", null, new { @class = "btn btn-info btn-block" })
    </p>
}@{ int i = 1;}
@foreach (var item in Model.Item1)
{    <hr class="hr_class" />
    <div class="row text_color">
        <div class="col-md-5 column">
            <h3>
                @Html.ActionLink(item.Title, "Index", "Subjects", new { id = item.CategoryID }, new { @class = "text_color" })
            </h3>
            <p class="description">
                @Html.DisplayFor(modelItem => item.Description)
            </p>
            @if (this.User.IsInRole("Administrator"))
            {
                <div class="row">
                    <div class="col-xs-2">
                        <p> @Html.ActionLink("Edit", "Edit","Categories", new { id = item.CategoryID },null)</p>
                    </div>
                    <div class="col-xs-2">
                        <p> @Html.ActionLink("Delete", "Delete","Categories", new { id = item.CategoryID },null) </p>
                    </div>
                </div>
            }
        </div>
        <div class="col-md-2 column" id="ac@(item.CategoryID)">
            <script>
                
                $(document).ready(function () {
                    $.ajax({
                        type: 'GET',
                        contentType: 'application/json;charset=utf-8',
                        url: '@Url.Action("GetNumberOfSubjects","Home")',
                        data: { "id":@item.CategoryID},
                        dataType: 'json',
                        async: false,
                    }).done(function (data) {

                        var node2 = document.createElement('p');
                        var textnode2 = document.createTextNode(data.Count + ' subjects');
                        node2.appendChild(textnode2);
                        document.getElementById("ac" + @item.CategoryID).appendChild(node2);

                    }).fail(function (data) {
                        console.log("Error"); 
                    });
                           
                 });

            </script>
        </div>
        <div class="col-md-5 column" id="ap@(item.CategoryID)">
            <script>
                $(document).ready(function () {
                    $.ajax({
                        type: 'GET',
                        contentType: 'application/json;charset=utf-8',
                        url: '@Url.Action("GetLastSubject","Home")',
                        data: { "id":@item.CategoryID},
                        dataType: 'json',
                        async: false,
                    }).done(function (data) {

                        if (data.Count == 0) {
                            var node = document.createElement('p');
                            var textnode = document.createTextNode("Niciun subiect");
                            node.appendChild(textnode);
                            document.getElementById("ap" + @item.CategoryID).appendChild(node);
                        }
                        else {
                            var node1 = document.createElement('a');
                            var node2 = document.createElement('p');
                            var node3 = document.createElement('a');


                            node1.href = "/Messages/Index/" + data.SubjectID;
                            node1.title = data.Title;

                            node3.href = "/UserEdit/UserShow/" + data.UserID;

                            var date = new Date(parseInt(data.Date.substr(6)));
                            var seconds = date.getSeconds();
                            var minutes = date.getMinutes();
                            if (minutes < 10)
                                minutes = '0' + minutes;
                            if (seconds < 10)
                                seconds = '0' + seconds;
                            var hour = date.getHours();
                            var month = date.getUTCMonth() + 1;
                            var day = date.getUTCDate();
                            var year = date.getUTCFullYear();
                            newdate = day + "/" + month + "/" + year + ' ' + hour + ':' + minutes + ':' + seconds;
                        
                            var textnode1 = document.createTextNode(data.Title);
                            var textnode2 = document.createTextNode(newdate);
                            var textnode3 = document.createTextNode('Last subject by: ' + data.FirstName + ' ' + data.LastName)
                            node1.appendChild(textnode1);
                            node2.appendChild(textnode2);
                            node3.appendChild(textnode3);

                            document.getElementById("ap" + data.CategoryID).appendChild(node1);
                            document.getElementById("ap" + data.CategoryID).appendChild(node2);
                            document.getElementById("ap" + data.CategoryID).appendChild(node3);
                        }

                    }).fail(function (data) {
                        console.log("Error"); 
                    });
                           
                 });
            </script>
        </div>
    </div>
    i++;
}
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {

            $('.row').each(function () {
                var highestBox = 0;

                $(this).find('.column').each(function () {
                    if ($(this).height() > highestBox) {
                        highestBox = $(this).height();
                    }
                })

                $(this).find('.column').height(highestBox);
            });


        });
    </script>
}